### ISSUE TITLE
User story 8 - Add database

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#13]
## Value Proposition

**As a User**
**I want to** save the data in a database.
**so that** i can achieve my data from different devices.
​

## Description
<img width="868" alt="Bildschirmfoto 2023-07-26 um 13 02 45" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/ac1ddeea-e20b-474f-bb54-1e580950b3f0">

## Acceptance Criteria

- [ ] there should be a database for the data.
- [ ] the data for the SpotList and SpotInfo components are delivered from a database.
- [ ] the "Add a new spot" page functionality should add the data to the database.​
      

## Tasks

- [ ] Create a branch with name feature/database
- [ ] Create a MongoDB database
- [ ] Create a connect.js
- [ ] Create the data model
- [ ] SpotList and SpotInfo components should send a READ request to the database and display the data
- [ ] AddSpot component should send a Write request to the database and add the data to the database after clicking the submit button.

**Comment by Frank-Schaeske** [comment]
Hi Martin,

for my first US I got the following comment from Roland:

"The acceptance-criteria should not check technical implementations (that's for the tasks). They should define what happens in the app/browser like:"

Therefore I think you have to change your Acceptance Criteria. Maybe something like "The data that is entered in one browser can afterwards be viewed in a different browser"?

**Comment by FlorianNova** [comment]
lgtm
