### ISSUE TITLE
User story 10 - Delete modal

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#18]
## Value Proposition

**As a** User  
**I want to** click on a delete button and see a modal before I delete a spot or a additional information.
**so that** so that I am first asked to confirm whether I really want to delete or not and don't accidentally delete something and the information is simply gone.
​

## Description
<img width="313" alt="Bildschirmfoto 2023-08-02 um 12 08 17" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/68324c69-807e-400e-84a9-86a0a1556d44">

## Acceptance Criteria

- [ ] opens a new popup window to confirm the delete or cancel.
- [ ] cancel button closes the pop-up
- [ ] delete button closes the pop-up and delete the information.
      ​

## Tasks

- [ ] create a feature branch
- [ ] create a component for the modal
- [ ] implement the function of closing the modal window with the cancel button in the modal.
- [ ] implement the function of deleting the information or spot by clicking the delete button in the modal.
- [ ] implement the functionality for opening the model window when clicking the delete button of a additional Information or a spot.

**Comment by CJAkkuec** [comment]
I usually prefer to have the name of the feature branch be part of the task item, but that's not a life or death kinda thing. ;)
