### ISSUE TITLE
User story 11 - Integrate map

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#19]
## Value Proposition

**As a** User  
**I want to** see a map with a marker.
**so that** i don't have to find the longitude and latitude first and can see immediately where the corresponding spot is.
​

## Description
<img width="663" alt="Bildschirmfoto 2023-08-02 um 15 24 10" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/734ec1b6-95b4-438d-99dd-2ddf20020c72">

## Acceptance Criteria

- [ ] on the ADD A NEW SPOT page you can define the spot position with a dragabel marker.
- [ ] on the SPOT INFORMATION page the map with the corresponding marker must be displayed

## Tasks

- [ ] create a featured branch
- [ ] integrate the chosen library into the application
- [ ] add a map to the "ADD A NEW SPOT" page with interactive marker functionality.
- [ ] connect the marker location to the latitude and longitude in the spotSchema
- [ ] add a map to the "SPOT INFORMATION" page with a non-interactive marker.

**Comment by florianblaschke** [comment]
LGTM
