### ISSUE TITLE
User story 12 - User Login

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#23]
## Value Proposition

**As a** User  
**I want to** log in to the app.
**so that** i can manage my own spots.
​
## Description

<img width="456" alt="Bildschirmfoto 2023-08-08 um 23 00 45" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/cb313b7e-b26a-4a84-a89e-1f84d73dd236">

## Acceptance Criteria

- [ ] Upon successful login, you will redirected to the own Spotlist
      ​

## Tasks

- [ ] Create featured branch feature/Login
- [ ] implement the schema to the model
- [ ] Set up the NextAuth.js configuration with google or apple or github authentication
- [ ] Implement the redirection to the Spotlist

**Comment by JudithRe** [comment]
lgtm
