### ISSUE TITLE
User story 13 - Cloudinary upload    

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#24]
## Value Proposition

**As a** User
**I want to** be able to upload images
**so that** so that I can add it to a spot 
​

## Description
<img width="201" alt="Bildschirmfoto 2023-08-08 um 23 29 23" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/9ce49181-9387-48f5-b1da-c6d650dc3a1c">

## Acceptance Criteria

- [ ] there is an upload input on the spot information page
- [ ] if you upload an image its displayed and there is a button to delete the image
      ​

## Tasks

- [ ] create a fetured branch with a fitting name
- [ ] create a cloudinary access
- [ ] add the cloudinary connection to your project
- [ ] add the upload input to your spot page
