### ISSUE TITLE
User story 14 - Weather data

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#25]
## Value Proposition

**As a** User
**I want to** be able to view weather data on the spot information page  
**so that** I can be informed about the current weather conditions at that spot.
​

## Description
On the spot information page there is a dedicated section for weather information. This section will display relevant weather data for the spot.
​

## Acceptance Criteria

- [ ] There is a dedicated section on the spot information page for displaying weather data.
- [ ] The weather data accurately reflects the current conditions at the spot.
      ​

## Tasks

- [ ] Create a feature branch named  feature/weather-data
- [ ] Integrate the chosen API 
- [ ] implement the UI for the weather data section on the spot information page.
