### ISSUE TITLE
User story 3 - Spot Information

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#3]
## Value Proposition

**As a user** 
**I want to** displays a detail page of a surf spot.
**so that** i can retrieve the stored information on a surf spot from the list. 

## Description
<img width="324" alt="Bildschirmfoto 2023-07-19 um 17 45 08" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/3595e96d-16aa-49e4-a051-444f6bac4812">

## Acceptance Criteria

- [ ] header that displays the title of the page
- [ ] the stored information of a spot should be displayed

## Tasks

- [ ] create a featured branch SpotInfo
- [ ] render the header-component on top of page
- [ ] create the SpotInfo component that includes the saved Information of each spot
- [ ] render the SpotInfo component under the header 
- [ ]  add a style component (with different classes)

**Comment by Roland-Hufnagel** [comment]
Hey Martin, acceptance-criteria and tasks are not the same thing. 
the possibility to enter the name of a spot per click I cannot see in your wireframe.
What happens after clicking the submit-button in the UI?
