### ISSUE TITLE
User story 4 - Navigation

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#4]
## Value Proposition

**As a User**  
**I want to** to navigate on the page.
**so that** i can navigate between the existing "ADD A NEW SURFSPOT" and "YOUR HIDDEN SPOTS" pages. 
​

## Description
<img width="328" alt="Bildschirmfoto 2023-07-20 um 10 23 40" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/a8279b23-4e87-4518-ae42-fa4eb6ed16af">

## Acceptance Criteria

- [ ] if you click on the list button you will be taken to the page "YOUR HIDDEN SPOTS".
- [ ] clicking on the list button will take you to the "ADD A NEW SURFSPOT" page.
      ​

## Tasks

- [ ] create a feature-branch
- [ ] create a nav-component
- [ ] add a style component
- [ ] render the nav-component
