### ISSUE TITLE
User story 5 - Delete a existing surf spot. 

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#6]
## Value Proposition

**As a User**  
**I want to** delete a existing surf spot from the "YOUR HIDDEN SPOTS" list. 
**so that** a spot that is no longer needed or has been incorrectly created can be removed.
​

## Description
<img width="364" alt="Bildschirmfoto 2023-07-20 um 15 56 11" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/31e946be-a576-4bf5-b1ca-622942d3be5e">
​

## Acceptance Criteria

- [ ] when you press the button the spot must be removed from the "YOUR HIDDEN SPOTS" list.
- [ ] After removing the spot, you will be redirected to the "YOUR HIDDEN SPOTS" list.
      ​

## Tasks

- [ ] create a featured branch
- [ ] create the delete button
- [ ] implement the logic to the button that the spot is deleted from the list and redirects you to the list "YOUR HIDDEN SPOTS".
- [ ] add add style components

**Comment by ekat-br** [comment]
Hi @StrongCurrent, great user story!🚀

Just to understand it better: what exactly means "redirecting to the list"? Are you switching the page?

**Comment by StrongCurrent** [comment]
yes, you will be redirected to the page with the list "YOUR HIDDEN SPOTS" [US1](https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/issues/1)
