### ISSUE TITLE
User story 6 - Add additional Spot Information

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#7]
## Value Proposition

**As a User**
**I want to** add additional individual information to a spot.  
**so that** so that you can get more information about a spot than just the longitude and latitude.
​
## Description
<img width="586" alt="Bildschirmfoto 2023-07-20 um 20 19 11" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/7f5405ea-163c-4478-a813-fe1700ffa1b5">​

## Acceptance Criteria

- [ ] An input field with a label must be provided for the new information. 
- [ ] a submit button to save the entered information must be provided.
- [ ] After pressing the submit button "ADD THIS INFO", the new entry must be added under the heading "ADDITIONAL SPOT INFORMATION"
- [ ] If there is no entry, the message "THERE IS NO ENTRY YET" should appear instead. 
      ​

## Tasks

- [ ] create a featured branch.
- [ ] create the input field with a label in to the SpotInfo component.
- [ ] create the submit button "ADD THIS INFO" in to the SpotInfo component.
- [ ] create the title "ADDITIONAL SPOT INFORMATION" in to the SpotInfo component.
- [ ] implement the logic for the button.
- [ ] implement the logic for the message "THERE IS NO ENTRY YET".
- [ ] add some style.

**Comment by ekat-br** [comment]
LGTM🚀🤩
