### ISSUE TITLE
User story 7 - Delete additional Spot Information

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#8]
## Value Proposition

**As a User**
**I want to** delete additional information of a spot.  
**so that** information is no longer relevant or required can be removed.
​

## Description
<img width="366" alt="Bildschirmfoto 2023-07-20 um 20 49 02" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/f4462f68-c940-4218-b283-8048e8f97faa">
​

## Acceptance Criteria

- [ ] there must be a delete button for each entry under additional spot information
- [ ] after pressing the corresponding delete button, the entry will be deleted and disappears.
      ​

## Tasks

- [ ] create a featured branch.
- [ ] add delete button to each entry of the additional spot information in the SpotInfo component.
- [ ] implement the logic for the button.
- [ ] add some style.

**Comment by StrongCurrent** [comment]
hey @Roland-Hufnagel, thanks for your question and the approval. Yes it is a navigation i am dealing with in the [US4](https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/issues/4).
