### ISSUE TITLE
User story 8 - Edit spotname and additional spot Information

### ISSUE THREAD

**Issue by StrongCurrent** [StrongCurrent/HIDDEN-SURF-SPOTS_capstone#9]
## Value Proposition

**As a User**
**I want to** edit the Spotname and the additional information of a spot.  
**so that** existing information can be changed or typographical errors can be corrected.
​
## Description
<img width="363" alt="Bildschirmfoto 2023-07-20 um 21 21 47" src="https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/assets/131701063/728b57e8-82bd-4685-abf1-863ab659d0e9">

## Acceptance Criteria

- [ ] you should be able to click on the SPOTNAME and an already existing ADDITIONAL SPOT INFORMATION to edit it
      ​

## Tasks

- [ ] create a featured branch.
- [ ] implement the logic for the already existing ADDITIONAL SPOT INFORMATION
- [ ] implement the logic for the SPOTNAME
- [ ] add some style.

**Comment by Roland-Hufnagel** [comment]
This is okay but could be done a little bit better, e.g. 'implement the logic' is very inaccurate. You can think about it and at least offer some details, HOW to implement it. 
As in the last US I am wondering about the navigation at the bottom. Is it really implemented at this time?

**Comment by StrongCurrent** [comment]
Hey @Roland-Hufnagel, thanks for your feedback i will take it into due consideration in future user stories. the navigation i am dealing with in the [US4](https://github.com/StrongCurrent/HIDDEN-SURF-SPOTS_capstone/issues/4).
